services:
  heimdall:
    container_name: piselfhosting-heimdall
    image: lscr.io/linuxserver/heimdall:{{ component_version }}
    restart: unless-stopped
    ports:
      - "8090:80"
      - "8490:443"
    volumes:
      - "{{DATA_ROOT}}/heimdall/config:/config"
    environment:
      - "PUID={{PUID}}"
      - "PGID={{PGID}}"
      - "TZ={{TZ}}"
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true
