<?php
/*
 * phpMyAdmin configuration for PiSelfhosting
 * This file is generated by PiSelfhosting setup tool.
 */

// This is needed for cookie based authentication to encrypt password in cookie
$cfg['blowfish_secret'] = '{{ PHPMYADMIN_BLOWFISH_SECRET }}';

// Servers configuration
$i = 0;

// First server
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = '{{ PMA_HOST }}'; // Should be 'mariadb' internally in Docker network
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false; // Set to true if you want to login without a password

// User for advanced features (phpMyAdmin internal configuration storage)
// This is for phpMyAdmin to store settings like bookmarks, history etc.
// The database 'phpmyadmin' and tables will be created by the init.sql.template if used.
$cfg['Servers'][$i]['controlhost'] = '{{ PMA_HOST }}';
$cfg['Servers'][$i]['controlport'] = '3306';
$cfg['Servers'][$i]['controluser'] = '{{ DB_USER }}';
$cfg['Servers'][$i]['controlpass'] = '{{ DB_PASS }}';
$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmarks';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][$i]['recurring_events'] = 'pma__recurring_events';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';
$cfg['Servers'][$i]['processing_history'] = 'pma__processing_history';


// Directories for saving/loading files from server
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

// Default language
$cfg['DefaultLang'] = 'en';

// Theme
$cfg['ThemeDefault'] = 'pmahomme';

// Hide PHP startup errors
@ini_set('display_errors', '0');
error_reporting(E_ALL);

// Use https (important for Traefik/NPM)
$cfg['ForceSSL'] = true;

?>
