services:
  organizr:
    container_name: piselfhosting-organizr
    image: lscr.io/linuxserver/organizr:{{ component_version }}
    restart: unless-stopped
    ports:
      - "8095:80"
    volumes:
      - "{{DATA_ROOT}}/organizr/config:/config"
    environment:
      - "PUID={{PUID}}"
      - "PGID={{PGID}}"
      - "TZ={{TZ}}"
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true
