services:
  homer:
    container_name: piselfhosting-homer
    image: bcpierce/homer:{{ component_version }}
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - "{{DATA_ROOT}}/homer/assets:/www/assets"
    # Homer is simple and does not need PUID/PGID/TZ
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true
