# status: "untested"
# last_tested_version: "none"
# platform_notes: "None"
# breaking_changes: "None"
services:
  fluffychat-web:
    image: {{ image_name }}:{{ component_version }}
    container_name: piselfhosting-fluffychat-web
    restart: unless-stopped
    ports:
      - "{{ FLUFFYCHAT_HTTP_PORT }}:80"
    networks:
      - piselfhosting_net
    volumes:
      - "/var/lib/piselfhosting/config/fluffychat-web/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ DATA_ROOT }}/fluffychat-web/log:/var/log/nginx"

networks:
  piselfhosting_net:
    external: true