# status: "untested"
# last_tested_version: "none"
# platform_notes: "None"
# breaking_changes: "None"
services:
  fluffychat-web:
    container_name: piselfhosting-fluffychat-web
    build:
      context: https://github.com/HenkVanHoek/pish-fluffychat-web.git#main
      dockerfile: Dockerfile
    image: piselfhosting/fluffychat-web:{{ component_version }}
    pull_policy: build
    ports:
      - "{{ FLUFFYCHAT_WEB_PORT }}:80"
    volumes:
      - "{{ DATA_ROOT }}/fluffychat-web/config.js:/usr/share/nginx/html/config.js:ro"
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true