# status: "untested"
# last_tested_version: "none"
# platform_notes: "None"
# breaking_changes: "None"
services:
  fluffychat-web:
    container_name: piselfhosting-fluffychat-web
    build:
      context: https://github.com/HenkVanHoek/pish-fluffychat-web.git#main
      dockerfile: Dockerfile
    image: {{ image_name }}:{{ component_version }}
    pull_policy: build
    restart: unless-stopped
    ports:
      - "{{ FLUFFYCHAT_WEB_HTTP_PORT }}:80"
    networks:
      - piselfhosting_net
networks:
  piselfhosting_net:
    external: true