services:
  adguard-home:
    image: adguard/adguardhome:{{ component_version }}
    container_name: piselfhosting-adguard-home
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp" # Web UI port from metadata
      - "853:853/tcp"  # DNS-over-TLS
      - "443:443/tcp"  # DNS-over-HTTPS (if enabled, conflicts with proxies)
    volumes:
      - "{{DATA_ROOT}}/adguard-home/work:/opt/adguardhome/work"
      - "{{DATA_ROOT}}/adguard-home/config:/opt/adguardhome/conf"
    networks:
      - piselfhosting_net

networks:
  piselfhosting_net:
    external: true
